version: '3'

services:
  app:
    build:
      context: node
    container_name: app
    entrypoint: dockerize -wait tcp://db:3306 -timeout 20s docker-entrypoint.sh 
    command: node index.js
    volumes:
      - ./node:/usr/src/app
      - /usr/src/app/node_modules
    tty: true
    ports:
      - "3000:3000"
    restart: always
    depends_on:
      - db
    networks:
      - app-network

  db:
    build:
      context: db
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    ports:
      - "3306:3306"
    volumes:
      - db-volume:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - app-network

  nginx:
    build:
      context: nginx
    container_name: nginx
    ports:
      - "8080:80"
    depends_on:
      - db
      - app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db-volume:
